### ISSUE TITLE
<malloc.h> vs. <stdlib.h>

### ISSUE THREAD

**Issue by alexey-lysiuk** [sahaRatul/sela#7]
Just of of curiosity, why are you using non-standard `<malloc.h>` header instead of standard `<stdlib.h>`?
Yes, I know that `<malloc.h>` is present on many systems, but not on all of them.
For instance, that's the single reason why encoder and decoder are failing to build on OS X. A simple find-and-replace solved the problem though.

**Comment by sahaRatul** [comment]
I didn't know that malloc.h is absent on OS X. It will be fixed on upcoming commits
